//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Booking
    {
        public T_Booking()
        {
            this.T_SeatBooked = new HashSet<T_SeatBooked>();
        }
    
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public string BookingStatus { get; set; }
        public int SloatId { get; set; }
        public System.DateTime BookingDate { get; set; }
    
        public virtual T_Sloats T_Sloats { get; set; }
        public virtual T_Users T_Users { get; set; }
        public virtual ICollection<T_SeatBooked> T_SeatBooked { get; set; }
    }
}
