//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Movie
    {
        public T_Movie()
        {
            this.T_Sloats = new HashSet<T_Sloats>();
            this.T_Ratting = new HashSet<T_Ratting>();
        }
    
        public int MovieId { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public string Movie_Category { get; set; }
        public string Cast { get; set; }
        public string Description { get; set; }
        public System.DateTime Duration { get; set; }
        public string Language { get; set; }
    
        public virtual ICollection<T_Sloats> T_Sloats { get; set; }
        public virtual ICollection<T_Ratting> T_Ratting { get; set; }
    }
}
