//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Ratting
    {
        public int RattingId { get; set; }
        public int UserId { get; set; }
        public int MovieId { get; set; }
        public double Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual T_Movie T_Movie { get; set; }
        public virtual T_Users T_Users { get; set; }
    }
}
