//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Seat
    {
        public T_Seat()
        {
            this.T_SeatBooked = new HashSet<T_SeatBooked>();
            this.T_Cart = new HashSet<T_Cart>();
        }
    
        public int SeatId { get; set; }
        public string SeatRow { get; set; }
        public string SeatNumber { get; set; }
        public int TheaterId { get; set; }
    
        public virtual T_Theater T_Theater { get; set; }
        public virtual ICollection<T_SeatBooked> T_SeatBooked { get; set; }
        public virtual ICollection<T_Cart> T_Cart { get; set; }
    }
}
